source 'https://rubygems.org'

gem 'rails', '~>5.0.0'
gem 'sqlite3', '~> 1.3.13'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails', '~> 4.4'
gem 'turbolinks', '~> 5.2', '>= 5.2.1'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'coderay', "~> 1.0.8"
gem 'rdiscount', '~> 2.2', '>= 2.2.0.1'
gem 'twitter-bootstrap-rails', '~>2.2.8'
gem 'therubyracer', '~> 0.12.3', :platforms => :ruby

group :development, :test do
  gem 'byebug', '~> 11.1', '>= 11.1.3'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 2.1'
end
