source 'https://rubygems.org'

gem 'rails', '~>3.2'
gem 'sqlite3', '~> 1.3.6'

gem 'jquery-rails'
gem 'coderay', "~> 1.0.8"
gem 'rdiscount'

gem 'bigdecimal', '~> 1.4', '>= 1.4.4'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'therubyracer', :platforms => :ruby

  gem 'twitter-bootstrap-rails', '~> 2.2.8'
  gem 'less-rails'
  gem 'uglifier', '>= 1.0.3'
end
