source 'https://rubygems.org'

gem 'rails', '~>3.2'
gem 'sqlite3'

gem 'jquery-rails'
gem 'coderay', "~> 1.0.8"
gem 'rdiscount'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'therubyracer', :platforms => :ruby

  gem 'twitter-bootstrap-rails'
  gem 'less-rails'
  gem 'uglifier', '>= 1.0.3'
end
